### ISSUE TITLE
Demo page broken

### ISSUE THREAD

**Issue by letmaik** [mahmoodvcs/Leaflet.NACCoordinates#2]
Tested on latest Firefox.

**Comment by mahmoodvcs** [comment]
Works fine for me !! Tested on Firefox and Chrome and IE 11.

**Comment by letmaik** [comment]
Hi, sorry it appears it was caused by the HTTPS Everywhere browser 
extension which switches to https: 
https://mahmoodvcs.github.io/Leaflet.NACCoordinates/example/demo.html 
This doesn't work as leaflet's cdn has an invalid SSL certificate.

**Comment by valerio-bozzolan** [comment]
Hi all :) I've seen that the demo is a 404 now:

https://mahmoodvcs.github.io/Leaflet.NACCoordinates/example/demo.html
